# Generated by Django 2.1.5 on 2019-12-15 01:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='allotment_enddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 1, 4, 53, 556359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='allotment_startdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 1, 4, 53, 556359, tzinfo=utc)),
        ),
    ]
