# Generated by Django 2.1.5 on 2019-12-17 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ORC', '0002_auto_20191214_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='allotment_enddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 4, 46, 5, 803109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='allotment_startdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 4, 46, 5, 803109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workorder_id',
            field=models.AutoField(auto_created=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
